import fs from 'fs';
const list = await (await fetch('http://localhost:9225/json')).json();
const page = list.find((t) => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((r) => (ws.onopen = r));
let id = 0; const pending = new Map();
ws.onmessage = (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } };
const send = (method, params = {}) => new Promise((res) => { const i = ++id; pending.set(i, res); ws.send(JSON.stringify({ id: i, method, params })); });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 2, mobile: true });
await send('Page.navigate', { url: 'http://localhost:5173/?n='+Date.now() });
await sleep(3500);
await send('Runtime.evaluate', { expression: `window.scrollTo(0,0)` });
await sleep(800);
const r = await send('Page.captureScreenshot', { format: 'png' });
fs.writeFileSync('_shots/card.png', Buffer.from(r.result.data, 'base64'));
console.log('captured');
ws.close(); process.exit(0);
